# Default values for kube-secrets-init.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of Pods to launch.
replicaCount: 1

image:
  # -- Repository to pull the container image from.
  # repository: bporter2387/kube-secrets-init
  repository: doitintl/kube-secrets-init
  # -- Image [pull policy](https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  pullPolicy: Always # IfNotPresent
  # -- Overrides the image tag (default is the chart appVersion).
  # tag: "latest"
  tag: ""

# -- Image [pull secrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret)
imagePullSecrets: []

# -- Provide a name in place of the chart name for `app:` labels.
nameOverride: ""

# -- Provide a name to substitute for the full names of resources.
fullnameOverride: ""

# -- One of the supported secret providers:
#   - `google` (Google Cloud Secrets Manager)
#   - `aws` (AWS Secrets Manager and SSM Parameter Store)
provider: ""

# -- Fallback secret name to use when no image pull secret is found in a Pod.
defaultImagePullSecret: ""
# -- Namespace of the fallback secret name.
defaultImagePullSecretNamespace: ""

certificate:
  # -- Use jetstack/cert-manager for creating the necessary certificates.
  # This is usually preferred as cert-manager automatically renews certificates.
  # Mutually exclusive with `generate`.
  useCertManager: false
  # -- Generate the necessary certificates during chart install.
  # Mutually exclusive with `useCertManager`.
  generate: true
  # -- The name of the secret to use.
  # If not set and useCertManager or generate is true, a name is generated using the fullname template.
  secretName: ""

serviceAccount:
  # -- Whether a service account should be created.
  create: true
  # -- Annotations to add to the service account.
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

rbac:
  # -- Specifies whether RBAC resources should be created.
  # If disabled, the operator is responsible for creating the necessary resources based on the templates.
  create: true

# -- Custom annotations for a Pod.
podAnnotations: {}

# -- Pod [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/pod-v1/#security-context) for details.
podSecurityContext: {}
  # fsGroup: 2000

# -- Container [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/container/#security-context) for details.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceMonitor:
  # -- Enable Prometheus ServiceMonitor.
  enabled: false

  # -- Interval at which metrics should be scraped.
  interval: 30s

# -- Container resource [requests and limits](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/container/#resources) for details.
# @default -- No requests or limits.
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Autoscaling configuration (see [values.yaml](values.yaml) for details).
# @default -- Disabled by default.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- [Node selector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector) configuration.
nodeSelector: {}

# -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) for node taints.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/pod-v1/#scheduling) for details.
tolerations: []

# -- [Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) configuration.
# See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/pod-v1/#scheduling) for details.
affinity: {}

# -- [Namespace selector](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector)
# for the mutating webhook configuration.
# @default -- `kube-system` namespace is excluded.
namespaceSelector:
  matchExpressions:
    - key: name
      operator: NotIn
      values:
        - kube-system
  # matchLabels:
  #   secret-injection: enabled

# -- [Object selector](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector)
# for the mutating webhook configuration.
# @default -- Exclude objects labeled with `kube-init-secrets.doit-intl.com/mutate: skip`.
objectSelector:
  matchExpressions:
    - key: kube-init-secrets.doit-intl.com/mutate
      operator: NotIn
      values:
        - skip
